In [3]:
import pandas as pd
import json
import csv
import os

In [29]:
with open('./data/alltime.json', 'r') as f:
    data = json.load(f)

df = pd.DataFrame.from_dict(data)
df['date'] = pd.to_datetime(df['date'])
df['yearmonth'] = df['date'].dt.to_period('M')
df_grouped = df.groupby(['yearmonth', 'artist'])['duration'].sum().reset_index()
df_grouped['date'] = df_grouped['yearmonth'].dt.to_timestamp()
df_grouped.drop('yearmonth', axis=1, inplace=True)


df_grouped = df_grouped.rename(columns={'artist': 'name', 'duration': 'value'})
df_grouped['category'] = 'kpop'
df_grouped = df_grouped[['date', 'name', 'category', 'value']]

df_grouped.sort_values(['name', 'date'], inplace=True)
df_grouped['accumulated'] = df_grouped.groupby('name')['value'].cumsum()

df_grouped.drop('value', axis=1, inplace=True)
df_grouped = df_grouped.rename(columns={'accumulated': 'value'})
df_grouped.sort_values('date', inplace=True)


df_grouped[df_grouped['name'] == 'Park Kyung']

            date        name category     value
46    2018-03-01  Park Kyung     kpop   2641358
60    2018-07-01  Park Kyung     kpop   2654598
173   2018-08-01  Park Kyung     kpop   2863038
474   2018-09-01  Park Kyung     kpop   2864573
821   2018-10-01  Park Kyung     kpop   3172737
1077  2018-11-01  Park Kyung     kpop   3844605
1337  2018-12-01  Park Kyung     kpop   4872159
1557  2019-01-01  Park Kyung     kpop   5691900
1832  2019-02-01  Park Kyung     kpop   6682242
2150  2019-03-01  Park Kyung     kpop   7562771
2486  2019-04-01  Park Kyung     kpop   7795637
2793  2019-05-01  Park Kyung     kpop   8662169
3079  2019-06-01  Park Kyung     kpop   9361577
3357  2019-07-01  Park Kyung     kpop  10270660
3692  2019-08-01  Park Kyung     kpop  10753597
4278  2019-10-01  Park Kyung     kpop  12339034
4744  2019-11-01  Park Kyung     kpop  14358624
5223  2019-12-01  Park Kyung     kpop  16203578
5682  2020-01-01  Park Kyung     kpop  17653537
6146  2020-02-01  Park Kyung     kpop  21428879
6569  2020-03-01  Park Kyung     kpop  34657096
7028  2020-04-01  Park Kyung     kpop  39663869
7558  2020-05-01  Park Kyung     kpop  44167120
8068  2020-06-01  Park Kyung     kpop  46130136
8495  2020-07-01  Park Kyung     kpop  47042755
8972  2020-08-01  Park Kyung     kpop  48105567
9583  2020-09-01  Park Kyung     kpop  51019364
10213 2020-10-01  Park Kyung     kpop  51520143
10715 2020-11-01  Park Kyung     kpop  51710592
11348 2020-12-01  Park Kyung     kpop  52827600
12001 2021-01-01  Park Kyung     kpop  54275670
12612 2021-02-01  Park Kyung     kpop  55202776
13335 2021-03-01  Park Kyung     kpop  57670439
14184 2021-04-01  Park Kyung     kpop  59987924
14934 2021-05-01  Park Kyung     kpop  60658923
15734 2021-06-01  Park Kyung     kpop  61259540
16684 2021-07-01  Park Kyung     kpop  61729215
17483 2021-08-01  Park Kyung     kpop  62085179
18211 2021-09-01  Park Kyung     kpop  63002906
19103 2021-10-01  Park Kyung     kpop  64862710
20164 2021-11-01  Park Kyung     kpop  65545638
21257 2021-12-01  Park Kyung     kpop  65785622
22160 2022-01-01  Park Kyung     kpop  67833208
23033 2022-02-01  Park Kyung     kpop  68531806
23846 2022-03-01  Park Kyung     kpop  69450777
27800 2022-09-01  Park Kyung     kpop  69877283
29669 2022-12-01  Park Kyung     kpop  70106974
30530 2023-01-01  Park Kyung     kpop  71041967
31280 2023-02-01  Park Kyung     kpop  71495204
31839 2023-03-01  Park Kyung     kpop  71501787

In [28]:
df_grouped.to_csv('alltime-grouped-artist.csv', index=False)